### ISSUE TITLE
stegano hide fails while encoding data bigger than target image

### ISSUE THREAD

**Issue by paulolc** [steganogram/stegano-rs#121]
**Describe the bug**
stegano hide fails while encoding data bigger than target image

**To Reproduce**
```
$ ls -l
total 980
-rwxrwxrwx 1 user user 370539 Feb 11 18:49 kitten.png
-rwxrwxrwx 1 user user 627962 Feb 11 18:49 tiger.png

$ stegano hide --data tiger.png --in kitten.png --out out.png
thread 'main' panicked at /home/pt103441/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stegano-core-0.5.3/src/lib.rs:382:18:
Failed to hide message in media: ImageEncodingError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
The command should not fail and encode the data file (tiger.png) into the input image (kitten.png) and write it to output image (out.png)

**Additional context**
The command works for data sizes smaller than the target image. It seems after a certain threshold the command starts to fail.

** Attachments **
![kitten](https://github.com/steganogram/stegano-rs/assets/673004/6316705b-d48f-4ad7-8032-9f2d12ec1368)
![tiger](https://github.com/steganogram/stegano-rs/assets/673004/d9b85ce7-a315-4435-93e6-7d09c254d796)

** RUST_BACKTRACE=full **
```
$ stegano hide --data tiger.png --in kitten.png --out out.png
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stegano-core-0.5.3/src/lib.rs:382:18:
Failed to hide message in media: ImageEncodingError
stack backtrace:
   0:     0x55e5863e20c6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55e5863e20c6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e5863e20c6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55e5863e20c6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e586409ab0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55e586409ab0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55e5863e003f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55e5863e1ea4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55e5863e1ea4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55e5863e3727 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55e5863e3489 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55e5863e3bb8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55e5863e3a92 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x55e5863e25c6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55e5863e37f0 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55e5860f5de5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55e5860f6333 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x55e586109d4b - stegano_core::SteganoEncoder::hide::h410acb8b6154a859
  18:     0x55e5860ffaf9 - stegano::main::h8570879c0fd5c8a3
  19:     0x55e5860f9a43 - std::sys_common::backtrace::__rust_begin_short_backtrace::h75ac67cd7440b4bf
  20:     0x55e5860f9a5d - std::rt::lang_start::{{closure}}::h4a86a37165924b9f
  21:     0x55e5863d96f1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  22:     0x55e5863d96f1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  23:     0x55e5863d96f1 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  24:     0x55e5863d96f1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  25:     0x55e5863d96f1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  26:     0x55e5863d96f1 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  27:     0x55e5863d96f1 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  28:     0x55e5863d96f1 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  29:     0x55e5863d96f1 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  30:     0x55e5861007a5 - main
  31:     0x7f4d5bb79d90 - <unknown>
  32:     0x7f4d5bb79e40 - __libc_start_main
  33:     0x55e5860f65f5 - _start
  34:                0x0 - <unknown>
```

**Comment by sassman** [comment]
Thanks for reporting. 
The issue is that your input image is too small to absorb all the data. 

So even though the error message must be improved, there is unfortunately no way to have this case succeed. The only possibility you have is to upscale the input image to the dimensions that in needs to provide to accept this data.

So I would make this part of the error message, that it does give you something like:

```
Capacity Error: The provided input image is too small to accept all provided data. The image dimensions required are at least 10248x1296.
```
